apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eks-role-service
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints","namespaces", "configmaps", "secrets"]
  verbs: ["get", "watch", "list"]