kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: eks-role-binding
subjects:
- kind: ServiceAccount
  name: eks-sa
roleRef:
  kind: Role
  name: eks-role-service
  apiGroup: rbac.authorization.k8s.io